MvcProject/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Interfaces;
using DAL.Entities;
using MvcProject.Models;
using AutoMapper;

namespace MvcProject.Controllers
{
    public class PhotoController : Controller
    {
        private readonly IPhotoRepo _photos;

        public PhotoController(IPhotoRepo photos)
        {
            _photos = photos;
        }

        public ActionResult Index()
        {
            return View("Index", _photos.GetAll());
        }
        // GET: /Photo/Create

        public ActionResult Create()
        {
            Photo newPhoto = new Photo();

            var model = Mapper.Map<Photo, PhotoModel>(newPhoto);
            
            model.CreatedDate = DateTime.Today;
            
            return View(model);
        }
        // POST: /Photo/Create
     
        [HttpPost]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            var model = Mapper.Map<Photo, PhotoModel>(photo);
            model.CreatedDate = DateTime.Today;

            if (ModelState.IsValid)
            {
                //Is there a photo? If so save it
                if (image != null)
                {
                    model.ImageMimeType = image.ContentType;
                    model.PhotoFile = new byte[image.ContentLength];
                    image.InputStream.Read(model.PhotoFile, 0, image.ContentLength);
                }

                //Add the photo to the database and save it
                _photos.Create(photo);

                return RedirectToAction("Index");
            }

            return View(photo);
        }
    }
}

MvcProject/Views/Photo/Create.cshtml
@model MvcProject.Models.PhotoModel

@{
    ViewBag.Title = "Create New Photo";
}
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Create", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.Title):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </span>
    </div>

    <div>
        <span class="editor-label">
            Upload new @Html.LabelFor(model => model.PhotoFile):
        </span>
        <span class="editor-field">
            <input class="pic-upload-input" type="file" name="Image">
        </span>
    </div>

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.Description):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </span>
    </div>

   

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.CreatedDate):
        </span>
        <span class="editor-field">
            @Html.DisplayFor(model => model.CreatedDate)
        </span>
    </div>

   

    <p>
        <input type="submit" value="Create" />
        @Html.ActionLink("Back to List", "Index")
    </p>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

MvcProject/Views/Photo/Index.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>